### ISSUE TITLE
Full class breakdown with bad attribute

### ISSUE THREAD

**Issue by mbell1210** [woywoy123/AnalysisG#14]
Noticed when using the "el_isPrompt" and "mu_isPrompt" branches in Nominal_Loose tree. Both of these are essentially empty lists (I had small EventStop, so the compiled list was likely actually empty). The Electron and Muon classes then returned empty information when called, and there was no error message, so took a while to figure out what the problem was.

**Comment by woywoy123** [comment]
Did the latest update fix this issue? Because I made some changes to the underlying particle compiler.
