### ISSUE TITLE
Small bug with Neutrino Class

### ISSUE THREAD

**Issue by eleboulicaut** [woywoy123/AnalysisG#4]
If I have `c1`, `c2` (of type `Particles.Children`) and `nu` (of type `Particles.Neutrino`) and I do `sum([nu, c1, c2])`, I get an error "AttributeError: 'Neutrino' object has no attribute 'pt'". But if I do `sum([c1, c2, nu])` it works.  I'm guessing it has to do with how the sum is defined [here](https://github.com/woywoy123/AnalysisTopGNN/blob/210eb8ac1a8f130714d428a411e4081370dbe25d/src/EventTemplates/Templates/Particle.py#L86). Would it be easy to change so that a sum involving neutrinos can be done in any order?

**Comment by woywoy123** [comment]
Fixed in latest commit .
